### ISSUE TITLE
Python typing support

### ISSUE THREAD

**Issue by bfelbo** [paulknysh/blackbox#19]
Thanks for a great piece of code! Have you considered typing it?
That would make it easier to use and to improve on :)

**Comment by paulknysh** [comment]
Hi, what do you mean by "typing it"?

**Comment by bfelbo** [comment]
I mean adding [type hints](https://docs.python.org/3/library/typing.html). The most amazing part about this repo is that it's simple enough to easily extend as needed. As an outsider, it would be much easier to extend the code if e.g. all the function parameters had type hints.

Moreover, it would make the code easier to use as static type checkers like mypy and pyright would pick up passing the wrong inputs to `search_min`.

**Comment by paulknysh** [comment]
Thanks, I've never tried these, would be interesting to potentially add at some point.

**Comment by paulknysh** [comment]
Added in https://github.com/paulknysh/blackbox/pull/28
