### ISSUE TITLE
Comparison with scipy optimize

### ISSUE THREAD

**Issue by pedvide** [paulknysh/blackbox#2]
Hello,

Do you have a comparison with scipy's minimize function (https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.optimize.minimize.html#scipy.optimize.minimize), maybe even using the different methods?

I have created a simulation (https://github.com/pedvide/simetuc) that takes from 1s to maybe 1000s to solve. optimization of the few (1-5) free parameters is painfully slow for the longer simulations, so I'm interested in any improvement!

**Comment by paulknysh** [comment]
Hi,

I don't have a direct comparison with this function. I looked at the list of methods available for scipy.optimize.minimize() - they are all "general purpose" methods.

**blackbox** (procedure is described [here](https://arxiv.org/pdf/1605.00998.pdf), based on [this paper](http://link.springer.com/article/10.1007/s10898-004-0570-0)) is designed for a specific class of functions that are expensive and black-box. In short, method is evaluating given function at few points, and based on those values, constructs an approximation of given function, that is much cheaper to evaluate and optimize. Of course, there is a time spent on constructing/optimizing such approximation, but that time is negligible in comparison to the time spent on evaluations of expensive function. This time also can be significant, if the method is applied on cheap function. So method doesn't work well for cheap functions.

I'd say, for the function that takes 1 s to evaluate it's not obvious if **blackbox** will provide significant speedup (it depends). But I believe it will in case of 10 s and more (definitely for >100 s).

**Comment by pedvide** [comment]
Thanks for the explanation. I understand it now.
I'll try to test it with my simulations, and compare it to the general scipy.minimize approach.

**Comment by pedvide** [comment]
I suggest that you copy the license contents to the top of your python file. People will probably copy your program file but not your license file!
