### ISSUE TITLE
let the user choose the pool object

### ISSUE THREAD

**Issue by celliern** [paulknysh/blackbox#4]
It could be a good idea to have a `pool` argument which take an object with a `map` method.
That way, it will be easy to use other multiprocessing tools like ipyparallel, [dask.distributed](https://distributed.readthedocs.io/en/latest/) or [pathos](https://github.com/uqfoundation/pathos).

See [abcpmc](http://abcpmc.readthedocs.io/en/latest/abcpmc.html#sampler-module) for a similar implementation.

**Comment by paulknysh** [comment]
Thanks for your suggestion! I'll consider this.
