### ISSUE TITLE
LIcence

### ISSUE THREAD

**Issue by pycckuu** [paulknysh/blackbox#8]
I would like to use Blackbox as a part of my reactive-transport modeling tool for calibration. How would you like me to cite you in my [Github project](https://github.com/biogeochemistry/PorousMediaLab)?

**Comment by paulknysh** [comment]
Hi, thanks for asking. I don't think there is a fixed format. Something like that would be OK:

blackbox: A Python module for parallel optimization of expensive black-box functions (by Paul Knysh)
https://github.com/paulknysh/blackbox
